%global rust_toolchain rust >= 1.93.0

Name:           ouch
Version:        0.8.1
Release:        1%{?dist}
Summary:        Painless compression and decompression in the terminal

License:        MIT
URL:            https://github.com/ouch-org/ouch
Source0:        %{url}/archive/%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  clang-devel
BuildRequires:  %{rust_toolchain}
BuildRequires:  cargo

%description
ouch stands for Obvious Unified Compression Helper. It is a CLI tool for
compressing and decompressing various formats including tar, zip, 7z, gz,
zstd, xz, lzma, bzip2, lz4, rar, and brotli.

%prep
%autosetup

%build
OUCH_ARTIFACTS_FOLDER=completions cargo build --release %{?_smp_flags}

%install
install -D -m 0755 target/release/%{name} %{buildroot}%{_bindir}/%{name}

# Shell completions & man page generated by build.rs (clap_complete + clap_mangen)
# when OUCH_ARTIFACTS_FOLDER is set during %build
# Bash
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
install -m 0644 completions/ouch.bash %{buildroot}%{_datadir}/bash-completion/completions/%{name} 2>/dev/null || :

# Zsh
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions/
install -m 0644 completions/_ouch %{buildroot}%{_datadir}/zsh/site-functions/_%{name} 2>/dev/null || :

# Fish
mkdir -p %{buildroot}%{_datadir}/fish/vendor_completions.d/
install -m 0644 completions/ouch.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/%{name}.fish 2>/dev/null || :

# Man page
mkdir -p %{buildroot}%{_mandir}/man1/
install -m 0644 completions/ouch.1 %{buildroot}%{_mandir}/man1/%{name}.1 2>/dev/null || :

%files
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*
%dir %{_datadir}/bash-completion
%dir %{_datadir}/bash-completion/completions
%{_datadir}/bash-completion/completions/%{name}
%dir %{_datadir}/zsh
%dir %{_datadir}/zsh/site-functions
%{_datadir}/zsh/site-functions/_%{name}
%dir %{_datadir}/fish
%dir %{_datadir}/fish/vendor_completions.d
%{_datadir}/fish/vendor_completions.d/%{name}.fish

%changelog
* Sat Jul 11 2026 boobaa <xenialv7@gmail.com> - 0.8.1-1
- Update to 0.8.1

* Sun Jun 29 2026 boobaa <xenialv7@gmail.com> - 0.8.0-2
- Fix shell completion generation via build.rs OUCH_ARTIFACTS_FOLDER
- Add man page from clap_mangen

* Sun Jun 29 2026 boobaa <xenialv7@gmail.com> - 0.8.0-1
- Initial package for Fedora COPR
