%global rust_toolchain rust >= 1.95.0

Name:           yazi
Version:        26.5.6
Release:        1%{?dist}
Summary:        Blazing fast terminal file manager written in Rust, based on async I/O

License:        MIT
URL:            https://github.com/sxyazi/yazi
Source0:        %{url}/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  cmake
BuildRequires:  %{rust_toolchain}
BuildRequires:  cargo

%description
Yazi (means "duck") is a terminal file manager written in Rust, based on
non-blocking async I/O. It aims to provide an efficient, user-friendly, and
customizable file management experience.

Features:
- Full async I/O support — all I/O operations are asynchronous
- Powerful async task scheduling and management
- Built-in support for multiple file previewers
- Plugin system (Lua-based)
- Vim-like keybindings
- Customizable themes, layouts, and keybindings

%prep
%autosetup

%build
YAZI_GEN_COMPLETIONS=1 cargo build --release %{?_smp_flags}

%install
# Binaries
install -D -m 0755 target/release/yazi %{buildroot}%{_bindir}/yazi
install -D -m 0755 target/release/ya %{buildroot}%{_bindir}/ya

# Shell completions for yazi (generated by yazi-boot/build.rs)
# Bash
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
install -m 0644 yazi-boot/completions/yazi.bash \
  %{buildroot}%{_datadir}/bash-completion/completions/yazi 2>/dev/null || :
# Zsh
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions/
install -m 0644 yazi-boot/completions/_yazi \
  %{buildroot}%{_datadir}/zsh/site-functions/_yazi 2>/dev/null || :
# Fish
mkdir -p %{buildroot}%{_datadir}/fish/vendor_completions.d/
install -m 0644 yazi-boot/completions/yazi.fish \
  %{buildroot}%{_datadir}/fish/vendor_completions.d/yazi.fish 2>/dev/null || :

# Shell completions for ya (generated by yazi-cli/build.rs)
# Bash
install -m 0644 yazi-cli/completions/ya.bash \
  %{buildroot}%{_datadir}/bash-completion/completions/ya 2>/dev/null || :
# Zsh
install -m 0644 yazi-cli/completions/_ya \
  %{buildroot}%{_datadir}/zsh/site-functions/_ya 2>/dev/null || :
# Fish
install -m 0644 yazi-cli/completions/ya.fish \
  %{buildroot}%{_datadir}/fish/vendor_completions.d/ya.fish 2>/dev/null || :

%files
%license LICENSE
%doc README.md
%{_bindir}/yazi
%{_bindir}/ya
%dir %{_datadir}/bash-completion
%dir %{_datadir}/bash-completion/completions
%{_datadir}/bash-completion/completions/yazi
%{_datadir}/bash-completion/completions/ya
%dir %{_datadir}/zsh
%dir %{_datadir}/zsh/site-functions
%{_datadir}/zsh/site-functions/_yazi
%{_datadir}/zsh/site-functions/_ya
%dir %{_datadir}/fish
%dir %{_datadir}/fish/vendor_completions.d
%{_datadir}/fish/vendor_completions.d/yazi.fish
%{_datadir}/fish/vendor_completions.d/ya.fish

%changelog
* Fri Jul 10 2026 boobaa <xenialv7@gmail.com> - 26.5.6-1
- Initial package for Fedora COPR
